/*
 * Generated by Bluespec Compiler, version 2024.01-19-g4cbd4f58 (build 4cbd4f58)
 * 
 * On Fri Jun 21 06:47:14 UTC 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbCSA.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_2("FAILED %d + %d gave %d instead of %d", 36u);
static std::string const __str_literal_1("PASSED", 6u);


/* Constructor */
MOD_mkTbCSA::MOD_mkTbCSA(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_randomVal1_ignore(simHdl, "randomVal1_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal1_initialized(simHdl, "randomVal1_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal1_zaz(simHdl, "randomVal1_zaz", this, 8u, (tUInt8)0u),
    INST_randomVal2_ignore(simHdl, "randomVal2_ignore", this, 8u, (tUInt8)0u),
    INST_randomVal2_initialized(simHdl, "randomVal2_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_randomVal2_zaz(simHdl, "randomVal2_zaz", this, 8u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h691(2863311530u),
    DEF_v__h315(2863311530u)
{
  symbol_count = 13u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbCSA::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_randomVal1_every", SYM_RULE);
  init_symbol(&symbols[2u], "RL_randomVal1_every_1", SYM_RULE);
  init_symbol(&symbols[3u], "RL_randomVal2_every", SYM_RULE);
  init_symbol(&symbols[4u], "RL_randomVal2_every_1", SYM_RULE);
  init_symbol(&symbols[5u], "RL_test", SYM_RULE);
  init_symbol(&symbols[6u], "randomVal1_ignore", SYM_MODULE, &INST_randomVal1_ignore);
  init_symbol(&symbols[7u], "randomVal1_initialized", SYM_MODULE, &INST_randomVal1_initialized);
  init_symbol(&symbols[8u], "randomVal1_zaz", SYM_MODULE, &INST_randomVal1_zaz);
  init_symbol(&symbols[9u], "randomVal2_ignore", SYM_MODULE, &INST_randomVal2_ignore);
  init_symbol(&symbols[10u], "randomVal2_initialized", SYM_MODULE, &INST_randomVal2_initialized);
  init_symbol(&symbols[11u], "randomVal2_zaz", SYM_MODULE, &INST_randomVal2_zaz);
  init_symbol(&symbols[12u], "x__h945", SYM_DEF, &DEF_x__h945, 32u);
}


/* Rule actions */

void MOD_mkTbCSA::RL_randomVal1_every()
{
  tUInt8 DEF_new_value__h357;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h315 = rand32();
  DEF_new_value__h357 = (tUInt8)((tUInt8)255u & DEF_v__h315);
  INST_randomVal1_zaz.METH_wset(DEF_new_value__h357);
}

void MOD_mkTbCSA::RL_randomVal1_every_1()
{
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  INST_randomVal1_ignore.METH_wset(DEF_v__h389);
}

void MOD_mkTbCSA::RL_randomVal2_every()
{
  tUInt8 DEF_new_value__h733;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h691 = rand32();
  DEF_new_value__h733 = (tUInt8)((tUInt8)255u & DEF_v__h691);
  INST_randomVal2_zaz.METH_wset(DEF_new_value__h733);
}

void MOD_mkTbCSA::RL_randomVal2_every_1()
{
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  INST_randomVal2_ignore.METH_wset(DEF_v__h764);
}

void MOD_mkTbCSA::RL_test()
{
  tUInt8 DEF_high__h1140;
  tUInt32 DEF_x__h3571;
  tUInt8 DEF_y__h1364;
  tUInt8 DEF_y__h2021;
  tUInt8 DEF_y__h2675;
  tUInt8 DEF_x__h2020;
  tUInt8 DEF_y__h1466;
  tUInt8 DEF_y__h2185;
  tUInt8 DEF_y__h2839;
  tUInt8 DEF_x__h2184;
  tUInt8 DEF_y__h1530;
  tUInt8 DEF_x__h1529;
  tUInt8 DEF_y__h1468;
  tUInt8 DEF_x__h1467;
  tUInt8 DEF_x__h1465;
  tUInt8 DEF_y__h1366;
  tUInt8 DEF_x__h1365;
  tUInt8 DEF_x__h1363;
  tUInt8 DEF_y__h2837;
  tUInt8 DEF_x__h2836;
  tUInt8 DEF_y__h2775;
  tUInt8 DEF_y__h2673;
  tUInt8 DEF_x__h2672;
  tUInt8 DEF_b__h1267;
  tUInt8 DEF_y__h1528;
  tUInt8 DEF_x__h1527;
  tUInt8 DEF_y__h2183;
  tUInt8 DEF_x__h2182;
  tUInt8 DEF_y__h2123;
  tUInt8 DEF_y__h2777;
  tUInt8 DEF_x__h2122;
  tUInt8 DEF_x__h2774;
  tUInt8 DEF_y__h2121;
  tUInt8 DEF_x__h2120;
  tUInt8 DEF_y__h2019;
  tUInt8 DEF_x__h2018;
  tUInt8 DEF_a__h1266;
  tUInt8 DEF_x__h2898;
  tUInt8 DEF_b__h1269;
  tUInt8 DEF_a__h1268;
  tUInt8 DEF_b__h3235;
  tUInt8 DEF_a__h3234;
  tUInt8 DEF_b__h3281;
  tUInt8 DEF_a__h3280;
  tUInt8 DEF_b__h3327;
  tUInt8 DEF_a__h3326;
  tUInt8 DEF_b__h3373;
  tUInt8 DEF_a__h3372;
  tUInt8 DEF_c__h2007;
  tUInt8 DEF_a__h3232;
  tUInt8 DEF_c__h2661;
  tUInt8 DEF_x__h2366;
  tUInt8 DEF_b__h3233;
  tUInt8 DEF_c__h2109;
  tUInt8 DEF_a__h3278;
  tUInt8 DEF_c__h2763;
  tUInt8 DEF_x__h2422;
  tUInt8 DEF_b__h3279;
  tUInt8 DEF_c__h2171;
  tUInt8 DEF_a__h3324;
  tUInt8 DEF_c__h2825;
  tUInt8 DEF_x__h2478;
  tUInt8 DEF_b__h3325;
  tUInt8 DEF_c__h1352;
  tUInt8 DEF_x__h1711;
  tUInt8 DEF_c__h1454;
  tUInt8 DEF_x__h1767;
  tUInt8 DEF_c__h1516;
  tUInt8 DEF_x__h1823;
  tUInt8 DEF_a__h3370;
  tUInt8 DEF_b__h3371;
  tUInt8 DEF_sel__h1143;
  tUInt8 DEF_a__h1270;
  tUInt8 DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d129;
  tUInt32 DEF_realAns__h3442;
  tUInt32 DEF_v__h1133;
  tUInt8 DEF_b__h1577;
  tUInt8 DEF_b__h1515;
  tUInt8 DEF_b__h1453;
  tUInt8 DEF_b__h1351;
  tUInt8 DEF_b__h2232;
  tUInt8 DEF_b__h2170;
  tUInt8 DEF_b__h2108;
  tUInt8 DEF_b__h2006;
  tUInt8 DEF_a__h1576;
  tUInt8 DEF_a__h1514;
  tUInt8 DEF_a__h1452;
  tUInt8 DEF_a__h1350;
  tUInt8 DEF_a__h2231;
  tUInt8 DEF_a__h2169;
  tUInt8 DEF_a__h2107;
  tUInt8 DEF_a__h2005;
  DEF_x__h945 = INST_cycle.METH_read();
  DEF_x_wget__h634 = INST_randomVal2_zaz.METH_wget();
  DEF_x_wget__h250 = INST_randomVal1_zaz.METH_wget();
  DEF_v__h389 = INST_randomVal1_zaz.METH_whas() ? DEF_x_wget__h250 : (tUInt8)0u;
  DEF_a__h2005 = (tUInt8)(DEF_v__h389 >> 7u);
  DEF_a__h2107 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 6u));
  DEF_a__h2169 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 5u));
  DEF_a__h2231 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 4u));
  DEF_a__h1350 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 3u));
  DEF_a__h1452 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 2u));
  DEF_a__h1514 = (tUInt8)((tUInt8)1u & (DEF_v__h389 >> 1u));
  DEF_a__h1576 = (tUInt8)((tUInt8)1u & DEF_v__h389);
  DEF_v__h764 = INST_randomVal2_zaz.METH_whas() ? DEF_x_wget__h634 : (tUInt8)0u;
  DEF_b__h2006 = (tUInt8)(DEF_v__h764 >> 7u);
  DEF_b__h2108 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 6u));
  DEF_b__h2170 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 5u));
  DEF_b__h2232 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 4u));
  DEF_b__h1351 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 3u));
  DEF_b__h1453 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 2u));
  DEF_b__h1577 = (tUInt8)((tUInt8)1u & DEF_v__h764);
  DEF_b__h1515 = (tUInt8)((tUInt8)1u & (DEF_v__h764 >> 1u));
  DEF_cycle_5_EQ_128___d17 = DEF_x__h945 == 128u;
  DEF_cycle_5_EQ_0___d16 = DEF_x__h945 == 0u;
  DEF_realAns__h3442 = 511u & ((511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h389))) + (511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h764))));
  DEF_a__h3370 = DEF_a__h2231 ^ DEF_b__h2232;
  DEF_b__h3371 = (tUInt8)1u & ~DEF_a__h3370;
  DEF_x__h1823 = DEF_a__h1514 ^ DEF_b__h1515;
  DEF_c__h1516 = DEF_a__h1576 & DEF_b__h1577;
  DEF_x__h1767 = DEF_a__h1452 ^ DEF_b__h1453;
  DEF_x__h1711 = DEF_a__h1350 ^ DEF_b__h1351;
  DEF_x__h2478 = DEF_a__h2169 ^ DEF_b__h2170;
  DEF_c__h2171 = DEF_a__h2231 & DEF_b__h2232;
  DEF_a__h3324 = DEF_x__h2478 ^ DEF_c__h2171;
  DEF_x__h2422 = DEF_a__h2107 ^ DEF_b__h2108;
  DEF_x__h2366 = DEF_a__h2005 ^ DEF_b__h2006;
  DEF_x__h2898 = DEF_c__h2171 | DEF_a__h2231;
  DEF_c__h2825 = DEF_x__h2898 | DEF_b__h2232;
  DEF_b__h3325 = DEF_x__h2478 ^ DEF_c__h2825;
  DEF_x__h2122 = DEF_a__h2107 & DEF_b__h2108;
  DEF_y__h2183 = DEF_b__h2170 & DEF_c__h2171;
  DEF_y__h1528 = DEF_b__h1515 & DEF_c__h1516;
  DEF_y__h2837 = DEF_b__h2170 & DEF_c__h2825;
  DEF_x__h1365 = DEF_a__h1350 & DEF_b__h1351;
  DEF_x__h1467 = DEF_a__h1452 & DEF_b__h1453;
  DEF_x__h1529 = DEF_a__h1514 & DEF_b__h1515;
  DEF_y__h1530 = DEF_a__h1514 & DEF_c__h1516;
  DEF_x__h1527 = DEF_x__h1529 | DEF_y__h1530;
  DEF_c__h1454 = DEF_x__h1527 | DEF_y__h1528;
  DEF_y__h1468 = DEF_a__h1452 & DEF_c__h1454;
  DEF_x__h1465 = DEF_x__h1467 | DEF_y__h1468;
  DEF_x__h2184 = DEF_a__h2169 & DEF_b__h2170;
  DEF_y__h2839 = DEF_a__h2169 & DEF_c__h2825;
  DEF_x__h2836 = DEF_x__h2184 | DEF_y__h2839;
  DEF_c__h2763 = DEF_x__h2836 | DEF_y__h2837;
  DEF_b__h3279 = DEF_x__h2422 ^ DEF_c__h2763;
  DEF_y__h2777 = DEF_a__h2107 & DEF_c__h2763;
  DEF_x__h2774 = DEF_x__h2122 | DEF_y__h2777;
  DEF_y__h2775 = DEF_b__h2108 & DEF_c__h2763;
  DEF_c__h2661 = DEF_x__h2774 | DEF_y__h2775;
  DEF_b__h3233 = DEF_x__h2366 ^ DEF_c__h2661;
  DEF_y__h2673 = DEF_b__h2006 & DEF_c__h2661;
  DEF_y__h2185 = DEF_a__h2169 & DEF_c__h2171;
  DEF_x__h2182 = DEF_x__h2184 | DEF_y__h2185;
  DEF_c__h2109 = DEF_x__h2182 | DEF_y__h2183;
  DEF_a__h3278 = DEF_x__h2422 ^ DEF_c__h2109;
  DEF_y__h2121 = DEF_b__h2108 & DEF_c__h2109;
  DEF_y__h2123 = DEF_a__h2107 & DEF_c__h2109;
  DEF_x__h2120 = DEF_x__h2122 | DEF_y__h2123;
  DEF_c__h2007 = DEF_x__h2120 | DEF_y__h2121;
  DEF_a__h3232 = DEF_x__h2366 ^ DEF_c__h2007;
  DEF_y__h2019 = DEF_b__h2006 & DEF_c__h2007;
  DEF_y__h1466 = DEF_b__h1453 & DEF_c__h1454;
  DEF_c__h1352 = DEF_x__h1465 | DEF_y__h1466;
  DEF_y__h1366 = DEF_a__h1350 & DEF_c__h1352;
  DEF_x__h1363 = DEF_x__h1365 | DEF_y__h1366;
  DEF_x__h2020 = DEF_a__h2005 & DEF_b__h2006;
  DEF_y__h2021 = DEF_a__h2005 & DEF_c__h2007;
  DEF_x__h2018 = DEF_x__h2020 | DEF_y__h2021;
  DEF_a__h1266 = DEF_x__h2018 | DEF_y__h2019;
  DEF_y__h2675 = DEF_a__h2005 & DEF_c__h2661;
  DEF_x__h2672 = DEF_x__h2020 | DEF_y__h2675;
  DEF_b__h1267 = DEF_x__h2672 | DEF_y__h2673;
  DEF_y__h1364 = DEF_b__h1351 & DEF_c__h1352;
  DEF_sel__h1143 = DEF_x__h1363 | DEF_y__h1364;
  DEF_a__h1270 = (tUInt8)1u & ~DEF_sel__h1143;
  DEF_a__h3372 = DEF_a__h1270 & DEF_a__h3370;
  DEF_b__h3373 = DEF_sel__h1143 & DEF_b__h3371;
  DEF_a__h3326 = DEF_a__h1270 & DEF_a__h3324;
  DEF_b__h3327 = DEF_sel__h1143 & DEF_b__h3325;
  DEF_a__h3280 = DEF_a__h1270 & DEF_a__h3278;
  DEF_b__h3281 = DEF_sel__h1143 & DEF_b__h3279;
  DEF_b__h3235 = DEF_sel__h1143 & DEF_b__h3233;
  DEF_a__h3234 = DEF_a__h1270 & DEF_a__h3232;
  DEF_a__h1268 = DEF_a__h1270 & DEF_a__h1266;
  DEF_b__h1269 = DEF_sel__h1143 & DEF_b__h1267;
  DEF_x__h3571 = DEF_x__h945 + 1u;
  DEF_high__h1140 = (tUInt8)31u & ((((((DEF_a__h1268 | DEF_b__h1269) << 4u) | ((DEF_a__h3234 | DEF_b__h3235) << 3u)) | ((DEF_a__h3280 | DEF_b__h3281) << 2u)) | ((DEF_a__h3326 | DEF_b__h3327) << 1u)) | (DEF_a__h3372 | DEF_b__h3373));
  DEF_v__h1133 = 511u & (((((((tUInt32)(DEF_high__h1140)) << 4u) | (((tUInt32)(DEF_x__h1711 ^ DEF_c__h1352)) << 3u)) | (((tUInt32)(DEF_x__h1767 ^ DEF_c__h1454)) << 2u)) | (((tUInt32)(DEF_x__h1823 ^ DEF_c__h1516)) << 1u)) | (tUInt32)(DEF_a__h1576 ^ DEF_b__h1577));
  DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d129 = !DEF_cycle_5_EQ_0___d16 && (!DEF_cycle_5_EQ_128___d17 && !(DEF_v__h1133 == DEF_realAns__h3442));
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal1_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_5_EQ_0___d16)
    INST_randomVal2_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_5_EQ_128___d17)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_5_EQ_128___d17)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d129)
      dollar_display(sim_hdl,
		     this,
		     "s,8,8,9,9",
		     &__str_literal_2,
		     DEF_v__h389,
		     DEF_v__h764,
		     DEF_v__h1133,
		     DEF_realAns__h3442);
    if (DEF_NOT_cycle_5_EQ_0_6_1_AND_NOT_cycle_5_EQ_128_7__ETC___d129)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h3571);
}


/* Methods */


/* Reset routines */

void MOD_mkTbCSA::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_randomVal2_initialized.reset_RST(ARG_rst_in);
  INST_randomVal1_initialized.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbCSA::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbCSA::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_randomVal1_ignore.dump_state(indent + 2u);
  INST_randomVal1_initialized.dump_state(indent + 2u);
  INST_randomVal1_zaz.dump_state(indent + 2u);
  INST_randomVal2_ignore.dump_state(indent + 2u);
  INST_randomVal2_initialized.dump_state(indent + 2u);
  INST_randomVal2_zaz.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbCSA::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 17u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_0___d16", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_5_EQ_128___d17", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h315", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h389", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h691", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h764", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h945", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h250", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h634", 8u);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_randomVal1_ignore.dump_VCD_defs(num);
  num = INST_randomVal1_initialized.dump_VCD_defs(num);
  num = INST_randomVal1_zaz.dump_VCD_defs(num);
  num = INST_randomVal2_ignore.dump_VCD_defs(num);
  num = INST_randomVal2_initialized.dump_VCD_defs(num);
  num = INST_randomVal2_zaz.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbCSA::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCSA &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbCSA::vcd_defs(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_0___d16) != DEF_cycle_5_EQ_0___d16)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_0___d16, 1u);
	backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      }
      ++num;
      if ((backing.DEF_cycle_5_EQ_128___d17) != DEF_cycle_5_EQ_128___d17)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_5_EQ_128___d17, 1u);
	backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      }
      ++num;
      if ((backing.DEF_v__h315) != DEF_v__h315)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h315, 32u);
	backing.DEF_v__h315 = DEF_v__h315;
      }
      ++num;
      if ((backing.DEF_v__h389) != DEF_v__h389)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h389, 8u);
	backing.DEF_v__h389 = DEF_v__h389;
      }
      ++num;
      if ((backing.DEF_v__h691) != DEF_v__h691)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h691, 32u);
	backing.DEF_v__h691 = DEF_v__h691;
      }
      ++num;
      if ((backing.DEF_v__h764) != DEF_v__h764)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h764, 8u);
	backing.DEF_v__h764 = DEF_v__h764;
      }
      ++num;
      if ((backing.DEF_x__h945) != DEF_x__h945)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h945, 32u);
	backing.DEF_x__h945 = DEF_x__h945;
      }
      ++num;
      if ((backing.DEF_x_wget__h250) != DEF_x_wget__h250)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h250, 8u);
	backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      }
      ++num;
      if ((backing.DEF_x_wget__h634) != DEF_x_wget__h634)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h634, 8u);
	backing.DEF_x_wget__h634 = DEF_x_wget__h634;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_0___d16, 1u);
      backing.DEF_cycle_5_EQ_0___d16 = DEF_cycle_5_EQ_0___d16;
      vcd_write_val(sim_hdl, num++, DEF_cycle_5_EQ_128___d17, 1u);
      backing.DEF_cycle_5_EQ_128___d17 = DEF_cycle_5_EQ_128___d17;
      vcd_write_val(sim_hdl, num++, DEF_v__h315, 32u);
      backing.DEF_v__h315 = DEF_v__h315;
      vcd_write_val(sim_hdl, num++, DEF_v__h389, 8u);
      backing.DEF_v__h389 = DEF_v__h389;
      vcd_write_val(sim_hdl, num++, DEF_v__h691, 32u);
      backing.DEF_v__h691 = DEF_v__h691;
      vcd_write_val(sim_hdl, num++, DEF_v__h764, 8u);
      backing.DEF_v__h764 = DEF_v__h764;
      vcd_write_val(sim_hdl, num++, DEF_x__h945, 32u);
      backing.DEF_x__h945 = DEF_x__h945;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h250, 8u);
      backing.DEF_x_wget__h250 = DEF_x_wget__h250;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h634, 8u);
      backing.DEF_x_wget__h634 = DEF_x_wget__h634;
    }
}

void MOD_mkTbCSA::vcd_prims(tVCDDumpType dt, MOD_mkTbCSA &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_randomVal1_ignore.dump_VCD(dt, backing.INST_randomVal1_ignore);
  INST_randomVal1_initialized.dump_VCD(dt, backing.INST_randomVal1_initialized);
  INST_randomVal1_zaz.dump_VCD(dt, backing.INST_randomVal1_zaz);
  INST_randomVal2_ignore.dump_VCD(dt, backing.INST_randomVal2_ignore);
  INST_randomVal2_initialized.dump_VCD(dt, backing.INST_randomVal2_initialized);
  INST_randomVal2_zaz.dump_VCD(dt, backing.INST_randomVal2_zaz);
}
