/*
 * Generated by Bluespec Compiler, version 2024.01-19-g4cbd4f58 (build 4cbd4f58)
 * 
 * On Fri Jun 21 06:47:12 UTC 2024
 * 
 */

/* Generation options: */
#ifndef __model_mkTbRCASimple_h__
#define __model_mkTbRCASimple_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTbRCASimple.h"

/* Class declaration for a model of mkTbRCASimple */
class MODEL_mkTbRCASimple : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTbRCASimple *mkTbRCASimple_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTbRCASimple();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTbRCASimple();
}

#endif /* ifndef __model_mkTbRCASimple_h__ */
