/*
 * Generated by Bluespec Compiler, version 2024.01-19-g4cbd4f58 (build 4cbd4f58)
 * 
 * On Fri Jun 21 06:48:20 UTC 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftInelasticPipeline_h__
#define __mkFftInelasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftInelasticPipeline module */
class MOD_mkFftInelasticPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Fifo<tUWide> INST_inFifo;
  MOD_Fifo<tUWide> INST_outFifo;
  MOD_Reg<tUWide> INST_sReg1;
  MOD_Reg<tUWide> INST_sReg2;
 
 /* Constructor */
 public:
  MOD_mkFftInelasticPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUWide DEF_sReg2___d5;
  tUInt8 DEF_inFifo_notEmpty____d1;
  tUInt8 DEF_sReg2_BIT_1024___d6;
 
 /* Local definitions */
 private:
  tUWide DEF_sReg1___d140;
  tUWide DEF_inFifo_first____d11;
  tUWide DEF_sReg1_40_BIT_1024_41_CONCAT_bfly_1_15_bfly4_22_ETC___d269;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d267;
  tUWide DEF_inFifo_notEmpty_CONCAT_bfly_0_15_bfly4_2251552_ETC___d139;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d137;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d397;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d394;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d264;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d134;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d391;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d131;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d261;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d388;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d128;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d258;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d385;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d125;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d255;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d382;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d122;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d252;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d379;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d119;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d249;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d376;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d116;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d246;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d373;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d113;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d243;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d370;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d110;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d240;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d367;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d107;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d237;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d364;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d104;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d234;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d361;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d101;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d231;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d358;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d98;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d228;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d355;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d95;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d225;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d352;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d92;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d222;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d349;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d89;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d219;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d344;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d84;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d214;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d339;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d79;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d209;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d334;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d74;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d204;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d329;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d69;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d199;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d324;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d64;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d194;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d319;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d59;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d189;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d314;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d54;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d184;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d309;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d49;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d179;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d304;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d44;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d174;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d299;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d39;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d169;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d294;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d34;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d164;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d289;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d29;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d159;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_sReg2_BITS_ETC___d284;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d24;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_sReg1_40_B_ETC___d154;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_doFft();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
};

#endif /* ifndef __mkFftInelasticPipeline_h__ */
