/*
 * Generated by Bluespec Compiler, version 2024.01-19-g4cbd4f58 (build 4cbd4f58)
 * 
 * On Fri Jun 21 06:48:35 UTC 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftElasticPipeline_h__
#define __mkFftElasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftElasticPipeline module */
class MOD_mkFftElasticPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Reg<tUWide> INST_fifo1_d_0;
  MOD_Reg<tUWide> INST_fifo1_d_1;
  MOD_Reg<tUWide> INST_fifo1_d_2;
  MOD_Reg<tUWide> INST_fifo2_d_0;
  MOD_Reg<tUWide> INST_fifo2_d_1;
  MOD_Reg<tUWide> INST_fifo2_d_2;
  MOD_Reg<tUWide> INST_inFifo_d_0;
  MOD_Reg<tUWide> INST_inFifo_d_1;
  MOD_Reg<tUWide> INST_inFifo_d_2;
  MOD_Reg<tUWide> INST_outFifo_d_0;
  MOD_Reg<tUWide> INST_outFifo_d_1;
  MOD_Reg<tUWide> INST_outFifo_d_2;
 
 /* Constructor */
 public:
  MOD_mkFftElasticPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_enq;
  tUInt8 PORT_EN_deq;
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_deq;
  tUInt8 DEF_WILL_FIRE_enq;
  tUInt8 DEF_outFifo_d_0_93_BIT_1024___d294;
  tUInt8 DEF_fifo2_d_0_52_BIT_1024___d153;
  tUInt8 DEF_fifo1_d_0_BIT_1024___d8;
  tUWide DEF_fifo2_d_2___d148;
  tUWide DEF_fifo2_d_0___d152;
  tUWide DEF_fifo1_d_2___d1;
  tUWide DEF_fifo1_d_0___d7;
  tUWide DEF_outFifo_d_2___d289;
  tUWide DEF_outFifo_d_0___d293;
  tUWide DEF_inFifo_d_2___d147;
  tUWide DEF_inFifo_d_0___d4;
  tUInt8 DEF_inFifo_d_0_BIT_1024___d5;
 
 /* Local definitions */
 private:
  tUInt8 DEF_outFifo_d_1_95_BIT_1024___d296;
  tUInt8 DEF_fifo2_d_1_54_BIT_1024___d155;
  tUInt8 DEF_fifo1_d_1_BIT_1024___d10;
  tUInt8 DEF_inFifo_d_1_43_BIT_1024___d144;
  tUWide DEF_fifo2_d_1___d154;
  tUWide DEF_fifo1_d_1___d9;
  tUWide DEF_outFifo_d_1___d295;
  tUWide DEF_inFifo_d_1___d143;
  tUWide DEF_IF_outFifo_d_1_95_BIT_1024_96_THEN_outFifo_d_1_ETC___d436;
  tUWide DEF__0_CONCAT_DONTCARE___d145;
  tUWide DEF_IF_inFifo_d_1_43_BIT_1024_44_THEN_inFifo_d_1_4_ETC___d146;
  tUWide DEF_IF_fifo2_d_1_54_BIT_1024_55_THEN_fifo2_d_1_54__ETC___d429;
  tUWide DEF_IF_fifo1_d_1_BIT_1024_0_THEN_fifo1_d_1_ELSE_0__ETC___d288;
  tUWide DEF__1_CONCAT_bfly_2_15_bfly4_2251552690364292668_f_ETC___d425;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d423;
  tUWide DEF__1_CONCAT_bfly_0_15_bfly4_2251552690364292668_i_ETC___d139;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d137;
  tUWide DEF__1_CONCAT_bfly_1_15_bfly4_2251552690364292668_f_ETC___d284;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d282;
  tUWide DEF__1_CONCAT_enq_in___d431;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d420;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d134;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d279;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d417;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d131;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d276;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d414;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d128;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d273;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d411;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d125;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d270;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d408;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d122;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d267;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d405;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d119;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d264;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d402;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d116;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d261;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d399;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d113;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d258;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d396;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d110;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d255;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d393;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d107;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d252;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d390;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d104;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d249;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d387;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d101;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d246;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d384;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d98;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d243;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d381;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d95;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d240;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d378;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d92;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d237;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d375;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d89;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d234;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d370;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d84;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d229;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d365;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d79;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d224;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d360;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d74;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d219;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d355;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d69;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d214;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d350;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d64;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d209;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d345;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d59;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d204;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d340;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d54;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d199;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d335;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d49;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d194;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d330;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d44;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d189;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d325;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d39;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d184;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d320;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d34;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d179;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d315;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d29;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d174;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_fifo2_d_0__ETC___d310;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_d_0_ETC___d24;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_fifo1_d_0__ETC___d169;
 
 /* Rules */
 public:
  void RL_stage0();
  void RL_stage1();
  void RL_stage2();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftElasticPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftElasticPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftElasticPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftElasticPipeline &backing);
};

#endif /* ifndef __mkFftElasticPipeline_h__ */
